version: '3.8'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend-network

  backend:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
